### ISSUE TITLE
Query Regarding App

### ISSUE THREAD

**Issue by aditmag** [sriram15/ForumAppPrototype#1]
Does this code create a forum ap where people can actually use it or is this only the Frontend and Design ?

**Comment by Rohankar123** [comment]
> Does this code create a forum ap where people can actually use it or is this only the Frontend and Design ?

This is just app design . people cant really use it

**Comment by sriram15** [comment]
@AlphaLaser This is just a old frontend project for learning flutter. It doesn't have the full functionality of a forum

**Comment by aditmag** [comment]
Got it. Thanks a lot
